[project]
name = "python-src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.21"
dependencies = [
    "opencv-python>=4.10.0.84",
    "tensorflow>=2.18.0",
]
